# Generated by Django 5.1.7 on 2025-03-30 02:23

import django.core.validators
import manage_owners_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_owners_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(help_text='First name of the client.', max_length=200, validators=[django.core.validators.MinLengthValidator(2), manage_owners_app.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(help_text='Last name of the client.', max_length=200, validators=[django.core.validators.MinLengthValidator(2), manage_owners_app.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text="Client's primary phone number.", max_length=20, validators=[django.core.validators.MinLengthValidator(2), manage_owners_app.validators.validate_phone_number]),
        ),
    ]
