# Generated by Django 5.1.7 on 2025-03-30 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_owners_app', '0002_alter_client_options_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('BILLING', 'Billing'), ('OTHER', 'Other')], default='HOME', help_text='Type of address.', max_length=10)),
                ('street_address_1', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=20, verbose_name='State / Province / Region')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal / Zip Code')),
                ('client', models.ForeignKey(help_text='The client this address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='manage_owners_app.client')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'unique_together': {('client', 'address_type')},
            },
        ),
    ]
