# Generated by Django 5.1.7 on 2025-03-31 18:29

import django.core.validators
import manage_owners_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_owners_app', '0003_remove_client_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='City name. Required.', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(help_text='Postal or ZIP code. Required.', max_length=20, verbose_name='Postal / Zip Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_province',
            field=models.CharField(blank=True, help_text='State, province, or region name. Optional.', max_length=50, verbose_name='State / Province / Region'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_1',
            field=models.CharField(help_text="Primary street address line (e.g., '123 Main St'). Required.", max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_2',
            field=models.CharField(blank=True, help_text="Secondary street address line (e.g., 'Apt 4B', 'Suite 100'). Optional.", max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text="Client's primary email address. Required.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(help_text='First name of the client. Required.', max_length=200, validators=[django.core.validators.MinLengthValidator(2), manage_owners_app.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(help_text='Last name of the client. Required.', max_length=200, validators=[django.core.validators.MinLengthValidator(2), manage_owners_app.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the client. Optional.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text="Client's primary phone number. Required.", max_length=20, validators=[django.core.validators.MinLengthValidator(2), manage_owners_app.validators.validate_phone_number]),
        ),
    ]
